name: PlugProtect
main: su.stash.PlugProtect.Main
version: 1.0
description: The all-in-one solution for server protection.
author: StashCat
commands:
   plugprotect:
      description: PlugProtect main command.
      usage: /plugprotect
      aliases: [pp]
      permission: plugprotect
      permission-message: Insufficient permission.
      default: false

permissions:
   plugprotect:
     description: Allows usage of the /plugprotect command.
     default: false

   plugprotect.manage:
     description: Allows basic own plot management.
     default: false

   plugprotect.manage.other:
     description: Allows managing other player plots.
     default: false

   plugprotect.player:
     description: Basic player permissions.
     default: true
     children:
      plugprotect.manage: true

   plugprotect.admin:
     description: Administrator/moderator permissions.
     default: op
     children:
      plugprotect.player: true
      plugprotect.manage.other: true
